import Head from 'next/head'
import ActivisionLogo from '../assets/activision.svg'
import { Container } from '../styles/pages/Home'

const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Create Setup Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ActivisionLogo/>
      <h1>ReactJS Structure</h1>
      <p>A ReactJS + NextJS structure made by Rocketseat</p>
    </Container>
  )
}

export default Home
